services:
  dnaforge-backend:
    build:
      context: .
      args:
        # Set NO_CUDA to any non-blank value to build and run this application without CUDA support
        # Also comment out the runtime setting
        NO_CUDA:
    image: lewimbes/dnaforge-backend
    container_name: dnaforge-backend
    # Comment the runtime setting out to build and run this application without CUDA support
    # Also set NO_CUDA to any non-blank value
    runtime: nvidia
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      # Define the location of the data directory in the container.
      DATADIR: /data/

      # Port number used in the container
      # If left blank, 8080 will be used.
      PORT: 8080

      # Host IP address
      # If left blank, 0.0.0.0 will be used.
      HOST: 0.0.0.0

      # Set a (random) access token to restrict access if your service is publicly available.
      # Use a reverse proxy and https, otherwise the token will be transmitted over an unencrypted connection.
      # If left blank, access is possible without any authentication.
      ACCESSTOKEN: ChangeMe

      # Specify the logging level. Possible values: ALL, TRACE, DEBUG, INFO, WARN, ERROR, OFF
      LOGLEVEL: INFO
