name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  gradle:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        task:
          - { name: check, cmd: "check --continue" }
          - { name: build, cmd: "build" }
          - { name: installDist, cmd: "installDist" }
    name: ${{ matrix.task.name }}

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Install oxDNA dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git cmake build-essential

      - name: Build oxDNA
        run: |
          git clone https://github.com/lorenzo-rovigatti/oxDNA.git
          cd oxDNA
          git switch --detach v3.7.0
          mkdir build
          cd build
          cmake ..
          make -j$(nproc)
          sudo cp bin/* /usr/local/bin/
          sudo cp src/liboxdna_common.* /usr/local/lib/ || true

      - name: run ${{ matrix.task.name }}
        run: ./gradlew ${{ matrix.task.cmd }}
